version: "3.5"
services:

  nginx:
    build:
      context: requirements/nginx
      dockerfile: dockerfile
    image: nginx-inception
    container_name: nginx-inception
    env_file: .env
    ports:
      - "443:443"
    volumes:
      - wordpress_vlm:/var/www/html/
    networks:
      - inception
    depends_on:
      - wordpress
    restart: always

  mariadb:
    build:
      context: requirements/mariadb
      dockerfile: dockerfile
    image: mariadb-inception
    container_name: mariadb-inception
    env_file: .env
    volumes:
      -  mariadb_vlm:/var/lib/mysql
    networks:
      - inception
    restart: always


  wordpress:
    build:
      context: requirements/wordpress
      dockerfile: dockerfile
    image: wordpress-inception
    container_name: wordpress-inception
    env_file: .env
    volumes:
      - wordpress_vlm:/var/www/html/
    networks:
      - inception
    depends_on:
      - mariadb
    restart: always
    
volumes:
  wordpress_vlm:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/tbeaudoi42/data/volume_wordpress
  mariadb_vlm:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/tbeaudoi42/data/volume_mariadb

networks:
    inception:
        name: inception
        driver: bridge

