version: "3.5"
services:
  nginx:
    build:
      context: requirements/nginx
      dockerfile: dockerfile
    container_name: nginx-inception
    ports:
      - "443:443"
    environment:
      - .env
    volumes:
      - ./requirements/wordpress/www/:/var/www/html/
    restart: always

  mariadb:
    build:
      context: requirements/mariadb
      dockerfile: dockerfile
    container_name: mariadb-inception
    # ports:
    #   - "443:443"
    # environment:
    #   - .env
    # restart: always

  # wordpress:
  #   build:
  #     context: ./requirements/wordpress
  #     dockerfile: dockerfile
  #   container_name: wordpress
  #   ports:
  #     - "443:443"
  #   environment:
  #     - .env
    # restart: always
