version: "3.5"
services:
  nginx:
    image: nginx_inception
    container_name: nginx
    ports:
      - "443:443"
    environment:
      - .env
    # restart: always

  mariadb:
    image: mariadb_inception
    container_name: mariadb
    # ports:
    #   - "443:443"
    # environment:
    #   - .env
    # restart: always

  # wordpress:
  #   build:
  #     context: ./requirements/wordpress
  #     dockerfile: dockerfile
  #   container_name: wordpress
  #   ports:
  #     - "443:443"
  #   environment:
  #     - .env
    # restart: always
